"use client";
import { useState, useEffect, useRef, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileSearch, Download, FileText } from "lucide-react";

import Header from "./components/Header";
import ScanInput from "./components/ScanInput";
import LiveFeed from "./components/LiveFeed";
import SummaryCards from "./components/SummaryCards";
import VulnerabilityCard from "./components/VulnerabilityCard";
import RiskMeter from "./components/RiskMeter";
import ScanProgress from "./components/ScanProgress";
import ScanHistory from "./components/ScanHistory";
import AttackCoverage from "./components/AttackCoverage";
import SeverityFilterBar, { type SeverityFilter } from "./components/SeverityFilterBar";

// ── Types ──────────────────────────────────────────────────────────────────────

interface FeedEvent {
    type: "probe" | "complete" | "error";
    probe?: number;
    attack_type?: string;
    success?: boolean;
    severity?: string;
    exposed?: string;
    payload_preview?: string;
    message?: string;
}

interface AttackResult {
    attack_type: string;
    payload: string;
    response: string;
    success: boolean;
    severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "NONE";
    exposed: string;
    explanation: string;
    fix: string;
}

interface ScanSummary {
    total_vulnerabilities: number;
    critical: number;
    high: number;
    medium: number;
    low: number;
    risk_score: number;
    total_probes: number;
}

interface ScanReport {
    scan_id: string;
    endpoint: string;
    status: string;
    summary: ScanSummary;
    vulnerabilities: AttackResult[];
    created_at: string;
}

// ── Markdown export helper ──────────────────────────────────────────────────

function generateMarkdown(report: ScanReport): string {
    const { scan_id, endpoint, status, summary, vulnerabilities, created_at } = report;
    const lines: string[] = [
        `# Baaz Security Report`,
        ``,
        `**Scan ID:** \`${scan_id}\`  `,
        `**Target:** ${endpoint}  `,
        `**Status:** ${status}  `,
        `**Date:** ${created_at}  `,
        ``,
        `---`,
        ``,
        `## Summary`,
        ``,
        `| Metric | Value |`,
        `|--------|-------|`,
        `| Risk Score | **${summary.risk_score} / 100** |`,
        `| Total Probes | ${summary.total_probes} |`,
        `| Total Vulnerabilities | ${summary.total_vulnerabilities} |`,
        `| Critical | 🔴 ${summary.critical} |`,
        `| High | 🟠 ${summary.high} |`,
        `| Medium | 🟡 ${summary.medium} |`,
        `| Low | 🟢 ${summary.low} |`,
        ``,
        `---`,
        ``,
        `## Vulnerabilities`,
        ``,
    ];

    if (vulnerabilities.length === 0) {
        lines.push(`✅ No vulnerabilities detected. All attack probes defended.`);
    } else {
        vulnerabilities.forEach((v, i) => {
            lines.push(
                `### ${i + 1}. [${v.severity}] ${v.attack_type.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase())}`,
                ``,
                `**Exposed:** ${v.exposed}`,
                ``,
                `**Payload:**`,
                `\`\`\``,
                v.payload,
                `\`\`\``,
                ``,
                `**AI Response:**`,
                `\`\`\``,
                v.response || "(no response)",
                `\`\`\``,
                ``,
                `**Analysis:** ${v.explanation}`,
                ``,
                `**Fix:** ${v.fix}`,
                ``,
                `---`,
                ``,
            );
        });
    }

    lines.push(`*Generated by [Baaz AI Security Scanner](http://localhost:3000)*`);
    return lines.join("\n");
}

// ── Page ───────────────────────────────────────────────────────────────────────

export default function HomePage() {
    const [scanId, setScanId] = useState<string | null>(null);
    const [isScanning, setIsScanning] = useState(false);
    const [feedEvents, setFeedEvents] = useState<FeedEvent[]>([]);
    const [probeCount, setProbeCount] = useState(0);
    const [report, setReport] = useState<ScanReport | null>(null);
    const [reportLoading, setReportLoading] = useState(false);
    const [severityFilter, setSeverityFilter] = useState<SeverityFilter>("ALL");
    const eventSourceRef = useRef<EventSource | null>(null);

    const fetchReport = useCallback(async (id: string) => {
        setReportLoading(true);
        try {
            const res = await fetch(`http://localhost:8000/scan/${id}`);
            if (res.ok) {
                const data = await res.json();
                setReport(data);
            }
        } catch { }
        setReportLoading(false);
    }, []);

    const handleScanStart = useCallback((id: string) => {
        setScanId(id);
        setIsScanning(true);
        setFeedEvents([]);
        setProbeCount(0);
        setReport(null);
        setSeverityFilter("ALL");

        if (eventSourceRef.current) eventSourceRef.current.close();

        const es = new EventSource(`http://localhost:8000/scan/${id}/stream`);
        eventSourceRef.current = es;

        es.onmessage = (event) => {
            const parsed: FeedEvent = JSON.parse(event.data);
            setFeedEvents((prev) => [...prev, parsed]);
            if (parsed.probe != null) setProbeCount(parsed.probe);

            if (parsed.type === "complete" || parsed.type === "error") {
                setIsScanning(false);
                es.close();
                setTimeout(() => fetchReport(id), 800);
            }
        };

        es.onerror = () => { setIsScanning(false); es.close(); };
    }, [fetchReport]);

    // Load an existing scan from history
    const handleLoadHistoryScan = useCallback(async (id: string) => {
        setIsScanning(false);
        setFeedEvents([]);
        setProbeCount(0);
        setScanId(id);
        await fetchReport(id);
    }, [fetchReport]);

    useEffect(() => () => { eventSourceRef.current?.close(); }, []);

    // Derived: filtered vulns + severity counts
    const allVulns = report?.vulnerabilities ?? [];
    const severityCounts = allVulns.reduce<Record<string, number>>((acc, v) => {
        acc[v.severity] = (acc[v.severity] ?? 0) + 1;
        return acc;
    }, {});
    const filteredVulns = severityFilter === "ALL"
        ? allVulns
        : allVulns.filter((v) => v.severity === severityFilter);

    // Download helpers
    const handleDownloadJSON = () => {
        if (!report) return;
        const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `baaz-report-${report.scan_id.slice(0, 8)}.json`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const handleDownloadMarkdown = () => {
        if (!report) return;
        const blob = new Blob([generateMarkdown(report)], { type: "text/markdown" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `baaz-report-${report.scan_id.slice(0, 8)}.md`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="min-h-screen bg-background grid-bg">
            <Header />

            {/* Hero section */}
            <div className="relative overflow-hidden">
                <div className="absolute inset-0 bg-glow-primary opacity-50 pointer-events-none" />
                <div className="max-w-7xl mx-auto px-6 py-12 text-center relative z-10">
                    <motion.div
                        initial={{ opacity: 0, y: -16 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                    >
                        <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-mono font-bold mb-5 uppercase tracking-widest">
                            <span className="relative flex h-1.5 w-1.5">
                                <span className="ping-ring absolute inline-flex h-full w-full rounded-full bg-primary opacity-75" />
                                <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-primary" />
                            </span>
                            AI Red-Team Scanner
                        </span>
                        <h1 className="text-5xl sm:text-7xl font-black tracking-tight text-text-primary mb-4">
                            Hunt AI<br />
                            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-accent-cyan to-accent-purple">
                                Vulnerabilities
                            </span>
                        </h1>
                        <p className="text-text-secondary text-lg max-w-2xl mx-auto">
                            Baaz autonomously fires{" "}
                            <span className="text-text-primary font-semibold">20 targeted attack probes</span> across
                            prompt injection, jailbreaking, data extraction, and privilege escalation — then uses an
                            LLM judge to assess each result.
                        </p>
                    </motion.div>
                </div>
            </div>

            <main className="max-w-7xl mx-auto px-6 pb-20 space-y-5">

                {/* Scan input */}
                <ScanInput onScanStart={handleScanStart} isScanning={isScanning} />

                {/* Scan progress bar — only visible while scanning */}
                <ScanProgress totalProbes={probeCount} isScanning={isScanning} />

                {/* Summary cards */}
                <SummaryCards summary={report?.summary ?? null} />

                {/* Three-column layout: live feed (2/3) + right sidebar (1/3) */}
                <div className="grid lg:grid-cols-3 gap-5">
                    {/* Left 2/3 — live feed */}
                    <div className="lg:col-span-2 space-y-5">
                        <LiveFeed events={feedEvents} isScanning={isScanning} scanId={scanId} />

                        {/* Attack coverage chart — appears after scan */}
                        {report && (
                            <AttackCoverage
                                vulnerabilities={report.vulnerabilities}
                                totalProbes={report.summary.total_probes}
                            />
                        )}
                    </div>

                    {/* Right 1/3 — risk meter + history */}
                    <div className="space-y-5">
                        <RiskMeter score={report?.summary.risk_score ?? 0} />
                        <ScanHistory onLoadScan={handleLoadHistoryScan} activeScanId={scanId} />
                    </div>
                </div>

                {/* Vulnerability report section */}
                <AnimatePresence>
                    {(report || reportLoading) && (
                        <motion.section
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: 20 }}
                            transition={{ duration: 0.5 }}
                        >
                            {/* Report header */}
                            <div className="flex flex-wrap items-center gap-3 mb-4">
                                <div className="flex items-center gap-3 flex-1 min-w-0">
                                    <FileSearch className="w-5 h-5 text-primary shrink-0" />
                                    <h2 className="text-xl font-bold text-text-primary">Vulnerability Report</h2>
                                    {report && (
                                        <span className="chip">{report.vulnerabilities.length} found</span>
                                    )}
                                </div>

                                {/* Export buttons */}
                                {report && (
                                    <div className="flex items-center gap-2">
                                        <motion.button
                                            whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
                                            onClick={handleDownloadMarkdown}
                                            className="flex items-center gap-2 px-3.5 py-2 bg-surface border border-border rounded-xl text-xs font-semibold text-text-secondary hover:text-accent-cyan hover:border-accent-cyan/40 transition-all"
                                        >
                                            <FileText className="w-3.5 h-3.5" />
                                            Export .md
                                        </motion.button>
                                        <motion.button
                                            whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
                                            onClick={handleDownloadJSON}
                                            className="flex items-center gap-2 px-3.5 py-2 bg-surface border border-border rounded-xl text-xs font-semibold text-text-secondary hover:text-primary hover:border-primary/40 transition-all"
                                        >
                                            <Download className="w-3.5 h-3.5" />
                                            Export .json
                                        </motion.button>
                                    </div>
                                )}
                            </div>

                            {/* Severity filter chips */}
                            {report && report.vulnerabilities.length > 0 && (
                                <div className="mb-4">
                                    <SeverityFilterBar
                                        active={severityFilter}
                                        onChange={setSeverityFilter}
                                        counts={severityCounts}
                                    />
                                </div>
                            )}

                            {reportLoading && (
                                <div className="glass-card rounded-xl p-8 text-center text-text-muted font-mono animate-pulse">
                                    Building report...
                                </div>
                            )}

                            {report && report.vulnerabilities.length === 0 && (
                                <div className="glass-card rounded-xl p-8 text-center border border-accent-green/20">
                                    <p className="text-accent-green text-lg font-bold mb-1">✓ No Vulnerabilities Detected</p>
                                    <p className="text-text-muted text-sm">
                                        All 20 attack probes were successfully defended. The AI endpoint appears resilient.
                                    </p>
                                </div>
                            )}

                            {report && filteredVulns.length > 0 && (
                                <div className="space-y-3">
                                    {filteredVulns.map((v, i) => (
                                        <VulnerabilityCard key={`${v.attack_type}-${i}`} vuln={v} index={i} />
                                    ))}
                                </div>
                            )}

                            {report && filteredVulns.length === 0 && report.vulnerabilities.length > 0 && (
                                <div className="glass-card rounded-xl p-6 text-center text-text-muted text-sm">
                                    No vulnerabilities match the <strong>{severityFilter}</strong> filter.
                                </div>
                            )}
                        </motion.section>
                    )}
                </AnimatePresence>
            </main>

            <footer className="border-t border-border/30 py-6 text-center text-xs font-mono text-text-muted">
                Baaz AI Security Scanner · FastAPI + Next.js + Groq LLM Judge
            </footer>
        </div>
    );
}
